from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
from PySide2.QtSql import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1754, 1154)
        self.actionNew_Season = QAction(MainWindow)
        self.actionNew_Season.setObjectName(u"actionNew_Season")
        self.actionLoad_Season = QAction(MainWindow)
        self.actionLoad_Season.setObjectName(u"actionLoad_Season")
        self.actionGrabSeasonData = QAction(MainWindow)
        self.actionGrabSeasonData.setObjectName(u"actionGrabSeasonData")
        self.actionGrabSeasonData.setEnabled(False)
        self.actionWIS_Credentials = QAction(MainWindow)
        self.actionWIS_Credentials.setObjectName(u"actionWIS_Credentials")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.comboBoxPositionFilter = QComboBox(self.centralwidget)
        self.comboBoxPositionFilter.addItem("")
        self.comboBoxPositionFilter.addItem("")
        self.comboBoxPositionFilter.addItem("")
        self.comboBoxPositionFilter.addItem("")
        self.comboBoxPositionFilter.addItem("")
        self.comboBoxPositionFilter.addItem("")
        self.comboBoxPositionFilter.addItem("")
        self.comboBoxPositionFilter.addItem("")
        self.comboBoxPositionFilter.addItem("")
        self.comboBoxPositionFilter.addItem("")
        self.comboBoxPositionFilter.addItem("")
        self.comboBoxPositionFilter.setObjectName(u"comboBoxPositionFilter")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPositionFilter.sizePolicy().hasHeightForWidth())
        self.comboBoxPositionFilter.setSizePolicy(sizePolicy)
        self.comboBoxPositionFilter.setMinimumSize(QSize(45, 0))
        self.comboBoxPositionFilter.setMaximumSize(QSize(45, 30))
        self.comboBoxPositionFilter.setMaxVisibleItems(11)
        self.comboBoxPositionFilter.setMaxCount(11)

        self.verticalLayout.addWidget(self.comboBoxPositionFilter)

        self.recruit_tableView = QTableView(self.centralwidget)
        self.recruit_tableView.setObjectName(u"recruit_tableView")
        self.recruit_tableView.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recruit_tableView.sizePolicy().hasHeightForWidth())
        self.recruit_tableView.setSizePolicy(sizePolicy)
        self.recruit_tableView.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.recruit_tableView.setSortingEnabled(True)

        self.verticalLayout.addWidget(self.recruit_tableView)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1754, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menudata = QMenu(self.menubar)
        self.menudata.setObjectName(u"menudata")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menudata.menuAction())
        self.menuFile.addAction(self.actionWIS_Credentials)
        self.menuFile.addAction(self.actionNew_Season)
        self.menuFile.addAction(self.actionLoad_Season)
        self.menudata.addAction(self.actionGrabSeasonData)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"GD Recruit Helper", None))
        self.actionNew_Season.setText(QCoreApplication.translate("MainWindow", u"New Season", None))
        self.actionLoad_Season.setText(QCoreApplication.translate("MainWindow", u"Load Season", None))
        self.actionGrabSeasonData.setText(QCoreApplication.translate("MainWindow", u"Grab Season Data", None))
        self.actionWIS_Credentials.setText(QCoreApplication.translate("MainWindow", u"WIS Credentials", None))
        self.comboBoxPositionFilter.setItemText(0, QCoreApplication.translate("MainWindow", u"ALL", None))
        self.comboBoxPositionFilter.setItemText(1, QCoreApplication.translate("MainWindow", u"QB", None))
        self.comboBoxPositionFilter.setItemText(2, QCoreApplication.translate("MainWindow", u"RB", None))
        self.comboBoxPositionFilter.setItemText(3, QCoreApplication.translate("MainWindow", u"WR", None))
        self.comboBoxPositionFilter.setItemText(4, QCoreApplication.translate("MainWindow", u"TE", None))
        self.comboBoxPositionFilter.setItemText(5, QCoreApplication.translate("MainWindow", u"OL", None))
        self.comboBoxPositionFilter.setItemText(6, QCoreApplication.translate("MainWindow", u"DL", None))
        self.comboBoxPositionFilter.setItemText(7, QCoreApplication.translate("MainWindow", u"LB", None))
        self.comboBoxPositionFilter.setItemText(8, QCoreApplication.translate("MainWindow", u"LB", None))
        self.comboBoxPositionFilter.setItemText(9, QCoreApplication.translate("MainWindow", u"K", None))
        self.comboBoxPositionFilter.setItemText(10, QCoreApplication.translate("MainWindow", u"P", None))

    #if QT_CONFIG(tooltip)
        self.comboBoxPositionFilter.setToolTip(QCoreApplication.translate("MainWindow", u"Position Filter", None))
    #endif // QT_CONFIG(tooltip)
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menudata.setTitle(QCoreApplication.translate("MainWindow", u"Data", None))
    # retranslateUi