from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_DialogShowColumns(object):
    def setupUi(self, DialogShowColumns):
        if not DialogShowColumns.objectName():
            DialogShowColumns.setObjectName(u"DialogShowColumns")
        DialogShowColumns.resize(506, 575)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogShowColumns.sizePolicy().hasHeightForWidth())
        DialogShowColumns.setSizePolicy(sizePolicy)
        DialogShowColumns.setMinimumSize(QSize(506, 575))
        DialogShowColumns.setMaximumSize(QSize(506, 575))
        font = QFont()
        font.setFamily(u"Arial")
        font.setPointSize(12)
        DialogShowColumns.setFont(font)
        self.gridLayout = QGridLayout(DialogShowColumns)
        self.gridLayout.setObjectName(u"gridLayout")
        self.checkBoxPot = QCheckBox(DialogShowColumns)
        self.checkBoxPot.setObjectName(u"checkBoxPot")
        sizePolicy.setHeightForWidth(self.checkBoxPot.sizePolicy().hasHeightForWidth())
        self.checkBoxPot.setSizePolicy(sizePolicy)
        self.checkBoxPot.setMinimumSize(QSize(145, 0))
        self.checkBoxPot.setMaximumSize(QSize(145, 16777215))
        self.checkBoxPot.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxPot, 10, 3, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.gridLayout.addItem(self.verticalSpacer, 23, 1, 1, 1)

        self.checkBoxGI = QCheckBox(DialogShowColumns)
        self.checkBoxGI.setObjectName(u"checkBoxGI")
        sizePolicy.setHeightForWidth(self.checkBoxGI.sizePolicy().hasHeightForWidth())
        self.checkBoxGI.setSizePolicy(sizePolicy)
        self.checkBoxGI.setMinimumSize(QSize(140, 0))
        self.checkBoxGI.setMaximumSize(QSize(140, 16777215))
        self.checkBoxGI.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxGI, 12, 2, 1, 1)

        self.checkBoxBLK = QCheckBox(DialogShowColumns)
        self.checkBoxBLK.setObjectName(u"checkBoxBLK")
        sizePolicy.setHeightForWidth(self.checkBoxBLK.sizePolicy().hasHeightForWidth())
        self.checkBoxBLK.setSizePolicy(sizePolicy)
        self.checkBoxBLK.setMinimumSize(QSize(140, 0))
        self.checkBoxBLK.setMaximumSize(QSize(140, 16777215))
        self.checkBoxBLK.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxBLK, 9, 2, 1, 1)

        self.checkBoxR1 = QCheckBox(DialogShowColumns)
        self.checkBoxR1.setObjectName(u"checkBoxR1")
        sizePolicy.setHeightForWidth(self.checkBoxR1.sizePolicy().hasHeightForWidth())
        self.checkBoxR1.setSizePolicy(sizePolicy)
        self.checkBoxR1.setMinimumSize(QSize(145, 0))
        self.checkBoxR1.setMaximumSize(QSize(145, 16777215))
        self.checkBoxR1.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxR1, 3, 3, 1, 1)

        self.checkBoxMiles = QCheckBox(DialogShowColumns)
        self.checkBoxMiles.setObjectName(u"checkBoxMiles")
        sizePolicy.setHeightForWidth(self.checkBoxMiles.sizePolicy().hasHeightForWidth())
        self.checkBoxMiles.setSizePolicy(sizePolicy)
        self.checkBoxMiles.setMinimumSize(QSize(145, 0))
        self.checkBoxMiles.setMaximumSize(QSize(145, 16777215))
        self.checkBoxMiles.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxMiles, 11, 1, 1, 1)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer, 1, 0, 1, 1)

        self.checkBoxTKL = QCheckBox(DialogShowColumns)
        self.checkBoxTKL.setObjectName(u"checkBoxTKL")
        sizePolicy.setHeightForWidth(self.checkBoxTKL.sizePolicy().hasHeightForWidth())
        self.checkBoxTKL.setSizePolicy(sizePolicy)
        self.checkBoxTKL.setMinimumSize(QSize(140, 0))
        self.checkBoxTKL.setMaximumSize(QSize(140, 16777215))
        self.checkBoxTKL.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxTKL, 10, 2, 1, 1)

        self.checkBoxDivision = QCheckBox(DialogShowColumns)
        self.checkBoxDivision.setObjectName(u"checkBoxDivision")
        sizePolicy.setHeightForWidth(self.checkBoxDivision.sizePolicy().hasHeightForWidth())
        self.checkBoxDivision.setSizePolicy(sizePolicy)
        self.checkBoxDivision.setMinimumSize(QSize(145, 0))
        self.checkBoxDivision.setMaximumSize(QSize(145, 16777215))
        self.checkBoxDivision.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxDivision, 13, 3, 1, 1)

        self.checkBoxHometown = QCheckBox(DialogShowColumns)
        self.checkBoxHometown.setObjectName(u"checkBoxHometown")
        sizePolicy.setHeightForWidth(self.checkBoxHometown.sizePolicy().hasHeightForWidth())
        self.checkBoxHometown.setSizePolicy(sizePolicy)
        self.checkBoxHometown.setMinimumSize(QSize(145, 0))
        self.checkBoxHometown.setMaximumSize(QSize(145, 16777215))
        self.checkBoxHometown.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxHometown, 10, 1, 1, 1)

        self.checkBoxGPA = QCheckBox(DialogShowColumns)
        self.checkBoxGPA.setObjectName(u"checkBoxGPA")
        sizePolicy.setHeightForWidth(self.checkBoxGPA.sizePolicy().hasHeightForWidth())
        self.checkBoxGPA.setSizePolicy(sizePolicy)
        self.checkBoxGPA.setMinimumSize(QSize(145, 0))
        self.checkBoxGPA.setMaximumSize(QSize(145, 16777215))
        self.checkBoxGPA.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxGPA, 9, 3, 1, 1)

        self.checkBoxR2 = QCheckBox(DialogShowColumns)
        self.checkBoxR2.setObjectName(u"checkBoxR2")
        sizePolicy.setHeightForWidth(self.checkBoxR2.sizePolicy().hasHeightForWidth())
        self.checkBoxR2.setSizePolicy(sizePolicy)
        self.checkBoxR2.setMinimumSize(QSize(145, 0))
        self.checkBoxR2.setMaximumSize(QSize(145, 16777215))
        self.checkBoxR2.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxR2, 4, 3, 1, 1)

        self.checkBoxRating = QCheckBox(DialogShowColumns)
        self.checkBoxRating.setObjectName(u"checkBoxRating")
        sizePolicy.setHeightForWidth(self.checkBoxRating.sizePolicy().hasHeightForWidth())
        self.checkBoxRating.setSizePolicy(sizePolicy)
        self.checkBoxRating.setMinimumSize(QSize(145, 0))
        self.checkBoxRating.setMaximumSize(QSize(145, 16777215))
        self.checkBoxRating.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxRating, 8, 1, 1, 1)

        self.checkBoxELU = QCheckBox(DialogShowColumns)
        self.checkBoxELU.setObjectName(u"checkBoxELU")
        sizePolicy.setHeightForWidth(self.checkBoxELU.sizePolicy().hasHeightForWidth())
        self.checkBoxELU.setSizePolicy(sizePolicy)
        self.checkBoxELU.setMinimumSize(QSize(140, 0))
        self.checkBoxELU.setMaximumSize(QSize(140, 16777215))
        self.checkBoxELU.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxELU, 13, 2, 1, 1)

        self.checkBoxTEC = QCheckBox(DialogShowColumns)
        self.checkBoxTEC.setObjectName(u"checkBoxTEC")
        sizePolicy.setHeightForWidth(self.checkBoxTEC.sizePolicy().hasHeightForWidth())
        self.checkBoxTEC.setSizePolicy(sizePolicy)
        self.checkBoxTEC.setMinimumSize(QSize(140, 0))
        self.checkBoxTEC.setMaximumSize(QSize(140, 16777215))
        self.checkBoxTEC.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxTEC, 14, 2, 1, 1)

        self.checkBoxID = QCheckBox(DialogShowColumns)
        self.checkBoxID.setObjectName(u"checkBoxID")
        sizePolicy.setHeightForWidth(self.checkBoxID.sizePolicy().hasHeightForWidth())
        self.checkBoxID.setSizePolicy(sizePolicy)
        self.checkBoxID.setMinimumSize(QSize(145, 0))
        self.checkBoxID.setMaximumSize(QSize(145, 16777215))
        self.checkBoxID.setLayoutDirection(Qt.LeftToRight)
        self.checkBoxID.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxID, 3, 1, 1, 1)

        self.verticalSpacer_3 = QSpacerItem(20, 30, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.gridLayout.addItem(self.verticalSpacer_3, 20, 1, 1, 1)

        self.checkBoxSigned = QCheckBox(DialogShowColumns)
        self.checkBoxSigned.setObjectName(u"checkBoxSigned")
        sizePolicy.setHeightForWidth(self.checkBoxSigned.sizePolicy().hasHeightForWidth())
        self.checkBoxSigned.setSizePolicy(sizePolicy)
        self.checkBoxSigned.setMinimumSize(QSize(145, 0))
        self.checkBoxSigned.setMaximumSize(QSize(145, 16777215))
        self.checkBoxSigned.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxSigned, 11, 3, 1, 1)

        self.checkBoxR4 = QCheckBox(DialogShowColumns)
        self.checkBoxR4.setObjectName(u"checkBoxR4")
        sizePolicy.setHeightForWidth(self.checkBoxR4.sizePolicy().hasHeightForWidth())
        self.checkBoxR4.setSizePolicy(sizePolicy)
        self.checkBoxR4.setMinimumSize(QSize(145, 0))
        self.checkBoxR4.setMaximumSize(QSize(145, 16777215))
        self.checkBoxR4.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxR4, 6, 3, 1, 1)

        self.checkBoxConsidering = QCheckBox(DialogShowColumns)
        self.checkBoxConsidering.setObjectName(u"checkBoxConsidering")
        sizePolicy.setHeightForWidth(self.checkBoxConsidering.sizePolicy().hasHeightForWidth())
        self.checkBoxConsidering.setSizePolicy(sizePolicy)
        self.checkBoxConsidering.setMinimumSize(QSize(145, 0))
        self.checkBoxConsidering.setMaximumSize(QSize(145, 16777215))
        self.checkBoxConsidering.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxConsidering, 12, 1, 1, 1)

        self.checkBoxRank = QCheckBox(DialogShowColumns)
        self.checkBoxRank.setObjectName(u"checkBoxRank")
        sizePolicy.setHeightForWidth(self.checkBoxRank.sizePolicy().hasHeightForWidth())
        self.checkBoxRank.setSizePolicy(sizePolicy)
        self.checkBoxRank.setMinimumSize(QSize(145, 0))
        self.checkBoxRank.setMaximumSize(QSize(145, 16777215))
        self.checkBoxRank.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxRank, 9, 1, 1, 1)

        self.checkBoxSTR = QCheckBox(DialogShowColumns)
        self.checkBoxSTR.setObjectName(u"checkBoxSTR")
        sizePolicy.setHeightForWidth(self.checkBoxSTR.sizePolicy().hasHeightForWidth())
        self.checkBoxSTR.setSizePolicy(sizePolicy)
        self.checkBoxSTR.setMinimumSize(QSize(140, 0))
        self.checkBoxSTR.setMaximumSize(QSize(140, 16777215))
        self.checkBoxSTR.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxSTR, 8, 2, 1, 1)

        self.labelShowColumns = QLabel(DialogShowColumns)
        self.labelShowColumns.setObjectName(u"labelShowColumns")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.labelShowColumns.sizePolicy().hasHeightForWidth())
        self.labelShowColumns.setSizePolicy(sizePolicy1)
        self.labelShowColumns.setMinimumSize(QSize(430, 0))
        self.labelShowColumns.setMaximumSize(QSize(430, 16777215))
        font1 = QFont()
        font1.setFamily(u"Arial")
        font1.setPointSize(16)
        self.labelShowColumns.setFont(font1)
        self.labelShowColumns.setStyleSheet(u"color: blue")
        self.labelShowColumns.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.labelShowColumns, 1, 1, 1, 3)

        self.checkBoxPos = QCheckBox(DialogShowColumns)
        self.checkBoxPos.setObjectName(u"checkBoxPos")
        sizePolicy.setHeightForWidth(self.checkBoxPos.sizePolicy().hasHeightForWidth())
        self.checkBoxPos.setSizePolicy(sizePolicy)
        self.checkBoxPos.setMinimumSize(QSize(145, 0))
        self.checkBoxPos.setMaximumSize(QSize(145, 16777215))
        self.checkBoxPos.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxPos, 5, 1, 1, 1)

        self.checkBoxATH = QCheckBox(DialogShowColumns)
        self.checkBoxATH.setObjectName(u"checkBoxATH")
        sizePolicy.setHeightForWidth(self.checkBoxATH.sizePolicy().hasHeightForWidth())
        self.checkBoxATH.setSizePolicy(sizePolicy)
        self.checkBoxATH.setMinimumSize(QSize(140, 0))
        self.checkBoxATH.setMaximumSize(QSize(140, 16777215))
        self.checkBoxATH.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxATH, 3, 2, 1, 1)

        self.checkBoxR3 = QCheckBox(DialogShowColumns)
        self.checkBoxR3.setObjectName(u"checkBoxR3")
        sizePolicy.setHeightForWidth(self.checkBoxR3.sizePolicy().hasHeightForWidth())
        self.checkBoxR3.setSizePolicy(sizePolicy)
        self.checkBoxR3.setMinimumSize(QSize(145, 0))
        self.checkBoxR3.setMaximumSize(QSize(145, 16777215))
        self.checkBoxR3.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxR3, 5, 3, 1, 1)

        self.checkBoxHAN = QCheckBox(DialogShowColumns)
        self.checkBoxHAN.setObjectName(u"checkBoxHAN")
        sizePolicy.setHeightForWidth(self.checkBoxHAN.sizePolicy().hasHeightForWidth())
        self.checkBoxHAN.setSizePolicy(sizePolicy)
        self.checkBoxHAN.setMinimumSize(QSize(140, 0))
        self.checkBoxHAN.setMaximumSize(QSize(140, 16777215))
        self.checkBoxHAN.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxHAN, 11, 2, 1, 1)

        self.checkBoxSTA = QCheckBox(DialogShowColumns)
        self.checkBoxSTA.setObjectName(u"checkBoxSTA")
        sizePolicy.setHeightForWidth(self.checkBoxSTA.sizePolicy().hasHeightForWidth())
        self.checkBoxSTA.setSizePolicy(sizePolicy)
        self.checkBoxSTA.setMinimumSize(QSize(140, 0))
        self.checkBoxSTA.setMaximumSize(QSize(140, 16777215))
        self.checkBoxSTA.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxSTA, 7, 2, 1, 1)

        self.checkBoxR5 = QCheckBox(DialogShowColumns)
        self.checkBoxR5.setObjectName(u"checkBoxR5")
        sizePolicy.setHeightForWidth(self.checkBoxR5.sizePolicy().hasHeightForWidth())
        self.checkBoxR5.setSizePolicy(sizePolicy)
        self.checkBoxR5.setMinimumSize(QSize(145, 0))
        self.checkBoxR5.setMaximumSize(QSize(145, 16777215))
        self.checkBoxR5.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxR5, 7, 3, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(20, 20, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.gridLayout.addItem(self.verticalSpacer_2, 2, 1, 1, 1)

        self.checkBoxDUR = QCheckBox(DialogShowColumns)
        self.checkBoxDUR.setObjectName(u"checkBoxDUR")
        sizePolicy.setHeightForWidth(self.checkBoxDUR.sizePolicy().hasHeightForWidth())
        self.checkBoxDUR.setSizePolicy(sizePolicy)
        self.checkBoxDUR.setMinimumSize(QSize(140, 0))
        self.checkBoxDUR.setMaximumSize(QSize(140, 16777215))
        self.checkBoxDUR.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxDUR, 5, 2, 1, 1)

        self.checkBoxWE = QCheckBox(DialogShowColumns)
        self.checkBoxWE.setObjectName(u"checkBoxWE")
        sizePolicy.setHeightForWidth(self.checkBoxWE.sizePolicy().hasHeightForWidth())
        self.checkBoxWE.setSizePolicy(sizePolicy)
        self.checkBoxWE.setMinimumSize(QSize(140, 0))
        self.checkBoxWE.setMaximumSize(QSize(140, 16777215))
        self.checkBoxWE.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxWE, 6, 2, 1, 1)

        self.checkBoxWeight = QCheckBox(DialogShowColumns)
        self.checkBoxWeight.setObjectName(u"checkBoxWeight")
        sizePolicy.setHeightForWidth(self.checkBoxWeight.sizePolicy().hasHeightForWidth())
        self.checkBoxWeight.setSizePolicy(sizePolicy)
        self.checkBoxWeight.setMinimumSize(QSize(145, 0))
        self.checkBoxWeight.setMaximumSize(QSize(145, 16777215))
        self.checkBoxWeight.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxWeight, 7, 1, 1, 1)

        self.checkBoxR6 = QCheckBox(DialogShowColumns)
        self.checkBoxR6.setObjectName(u"checkBoxR6")
        sizePolicy.setHeightForWidth(self.checkBoxR6.sizePolicy().hasHeightForWidth())
        self.checkBoxR6.setSizePolicy(sizePolicy)
        self.checkBoxR6.setMinimumSize(QSize(145, 0))
        self.checkBoxR6.setMaximumSize(QSize(145, 16777215))
        self.checkBoxR6.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxR6, 8, 3, 1, 1)

        self.checkBoxSPD = QCheckBox(DialogShowColumns)
        self.checkBoxSPD.setObjectName(u"checkBoxSPD")
        sizePolicy.setHeightForWidth(self.checkBoxSPD.sizePolicy().hasHeightForWidth())
        self.checkBoxSPD.setSizePolicy(sizePolicy)
        self.checkBoxSPD.setMinimumSize(QSize(140, 0))
        self.checkBoxSPD.setMaximumSize(QSize(140, 16777215))
        self.checkBoxSPD.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxSPD, 4, 2, 1, 1)

        self.checkBoxWatched = QCheckBox(DialogShowColumns)
        self.checkBoxWatched.setObjectName(u"checkBoxWatched")
        sizePolicy.setHeightForWidth(self.checkBoxWatched.sizePolicy().hasHeightForWidth())
        self.checkBoxWatched.setSizePolicy(sizePolicy)
        self.checkBoxWatched.setMinimumSize(QSize(145, 0))
        self.checkBoxWatched.setMaximumSize(QSize(145, 16777215))
        self.checkBoxWatched.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxWatched, 12, 3, 1, 1)

        self.checkBoxName = QCheckBox(DialogShowColumns)
        self.checkBoxName.setObjectName(u"checkBoxName")
        sizePolicy.setHeightForWidth(self.checkBoxName.sizePolicy().hasHeightForWidth())
        self.checkBoxName.setSizePolicy(sizePolicy)
        self.checkBoxName.setMinimumSize(QSize(145, 0))
        self.checkBoxName.setMaximumSize(QSize(145, 16777215))
        self.checkBoxName.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxName, 4, 1, 1, 1)

        self.checkBoxHeight = QCheckBox(DialogShowColumns)
        self.checkBoxHeight.setObjectName(u"checkBoxHeight")
        sizePolicy.setHeightForWidth(self.checkBoxHeight.sizePolicy().hasHeightForWidth())
        self.checkBoxHeight.setSizePolicy(sizePolicy)
        self.checkBoxHeight.setMinimumSize(QSize(145, 0))
        self.checkBoxHeight.setMaximumSize(QSize(145, 16777215))
        self.checkBoxHeight.setChecked(True)

        self.gridLayout.addWidget(self.checkBoxHeight, 6, 1, 1, 1)

        self.verticalSpacer_4 = QSpacerItem(20, 10, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.gridLayout.addItem(self.verticalSpacer_4, 0, 0, 1, 1)

        self.buttonBoxSaveCancel = QDialogButtonBox(DialogShowColumns)
        self.buttonBoxSaveCancel.setObjectName(u"buttonBoxSaveCancel")
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.buttonBoxSaveCancel.sizePolicy().hasHeightForWidth())
        self.buttonBoxSaveCancel.setSizePolicy(sizePolicy2)
        self.buttonBoxSaveCancel.setMinimumSize(QSize(430, 0))
        self.buttonBoxSaveCancel.setMaximumSize(QSize(16666, 16777215))
        font2 = QFont()
        font2.setFamily(u"Arial")
        font2.setPointSize(14)
        self.buttonBoxSaveCancel.setFont(font2)
        self.buttonBoxSaveCancel.setOrientation(Qt.Horizontal)
        self.buttonBoxSaveCancel.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Save)
        self.buttonBoxSaveCancel.setCenterButtons(True)

        self.gridLayout.addWidget(self.buttonBoxSaveCancel, 22, 0, 1, 4)

        QWidget.setTabOrder(self.checkBoxID, self.checkBoxName)
        QWidget.setTabOrder(self.checkBoxName, self.checkBoxPos)
        QWidget.setTabOrder(self.checkBoxPos, self.checkBoxHeight)
        QWidget.setTabOrder(self.checkBoxHeight, self.checkBoxWeight)
        QWidget.setTabOrder(self.checkBoxWeight, self.checkBoxRating)
        QWidget.setTabOrder(self.checkBoxRating, self.checkBoxRank)
        QWidget.setTabOrder(self.checkBoxRank, self.checkBoxHometown)
        QWidget.setTabOrder(self.checkBoxHometown, self.checkBoxMiles)
        QWidget.setTabOrder(self.checkBoxMiles, self.checkBoxConsidering)
        QWidget.setTabOrder(self.checkBoxConsidering, self.checkBoxATH)
        QWidget.setTabOrder(self.checkBoxATH, self.checkBoxSPD)
        QWidget.setTabOrder(self.checkBoxSPD, self.checkBoxDUR)
        QWidget.setTabOrder(self.checkBoxDUR, self.checkBoxWE)
        QWidget.setTabOrder(self.checkBoxWE, self.checkBoxSTA)
        QWidget.setTabOrder(self.checkBoxSTA, self.checkBoxSTR)
        QWidget.setTabOrder(self.checkBoxSTR, self.checkBoxBLK)
        QWidget.setTabOrder(self.checkBoxBLK, self.checkBoxTKL)
        QWidget.setTabOrder(self.checkBoxTKL, self.checkBoxHAN)
        QWidget.setTabOrder(self.checkBoxHAN, self.checkBoxGI)
        QWidget.setTabOrder(self.checkBoxGI, self.checkBoxELU)
        QWidget.setTabOrder(self.checkBoxELU, self.checkBoxTEC)
        QWidget.setTabOrder(self.checkBoxTEC, self.checkBoxR1)
        QWidget.setTabOrder(self.checkBoxR1, self.checkBoxR2)
        QWidget.setTabOrder(self.checkBoxR2, self.checkBoxR3)
        QWidget.setTabOrder(self.checkBoxR3, self.checkBoxR4)
        QWidget.setTabOrder(self.checkBoxR4, self.checkBoxR5)
        QWidget.setTabOrder(self.checkBoxR5, self.checkBoxR6)
        QWidget.setTabOrder(self.checkBoxR6, self.checkBoxGPA)
        QWidget.setTabOrder(self.checkBoxGPA, self.checkBoxPot)
        QWidget.setTabOrder(self.checkBoxPot, self.checkBoxSigned)
        QWidget.setTabOrder(self.checkBoxSigned, self.checkBoxWatched)
        QWidget.setTabOrder(self.checkBoxWatched, self.checkBoxDivision)

        self.retranslateUi(DialogShowColumns)
        self.buttonBoxSaveCancel.accepted.connect(DialogShowColumns.accept)
        self.buttonBoxSaveCancel.rejected.connect(DialogShowColumns.reject)

        QMetaObject.connectSlotsByName(DialogShowColumns)
    # setupUi

    def retranslateUi(self, DialogShowColumns):
        DialogShowColumns.setWindowTitle(QCoreApplication.translate("DialogShowColumns", u"Show Columns", None))
        self.checkBoxPot.setText(QCoreApplication.translate("DialogShowColumns", u"Pot", None))
        self.checkBoxGI.setText(QCoreApplication.translate("DialogShowColumns", u"GI", None))
        self.checkBoxBLK.setText(QCoreApplication.translate("DialogShowColumns", u"BLK", None))
        self.checkBoxR1.setText(QCoreApplication.translate("DialogShowColumns", u"R1", None))
        self.checkBoxMiles.setText(QCoreApplication.translate("DialogShowColumns", u"Miles", None))
        self.checkBoxTKL.setText(QCoreApplication.translate("DialogShowColumns", u"TKL", None))
        self.checkBoxDivision.setText(QCoreApplication.translate("DialogShowColumns", u"Division", None))
        self.checkBoxHometown.setText(QCoreApplication.translate("DialogShowColumns", u"Hometown", None))
        self.checkBoxGPA.setText(QCoreApplication.translate("DialogShowColumns", u"GPA", None))
        self.checkBoxR2.setText(QCoreApplication.translate("DialogShowColumns", u"R2", None))
        self.checkBoxRating.setText(QCoreApplication.translate("DialogShowColumns", u"Rating", None))
        self.checkBoxELU.setText(QCoreApplication.translate("DialogShowColumns", u"ELU", None))
        self.checkBoxTEC.setText(QCoreApplication.translate("DialogShowColumns", u"TEC", None))
        self.checkBoxID.setText(QCoreApplication.translate("DialogShowColumns", u"ID", None))
        self.checkBoxSigned.setText(QCoreApplication.translate("DialogShowColumns", u"Signed", None))
        self.checkBoxR4.setText(QCoreApplication.translate("DialogShowColumns", u"R4", None))
        self.checkBoxConsidering.setText(QCoreApplication.translate("DialogShowColumns", u"Considering", None))
        self.checkBoxRank.setText(QCoreApplication.translate("DialogShowColumns", u"Rank", None))
        self.checkBoxSTR.setText(QCoreApplication.translate("DialogShowColumns", u"STR", None))
        self.labelShowColumns.setText(QCoreApplication.translate("DialogShowColumns", u"Show Table Columns:", None))
        self.checkBoxPos.setText(QCoreApplication.translate("DialogShowColumns", u"Pos", None))
        self.checkBoxATH.setText(QCoreApplication.translate("DialogShowColumns", u"ATH", None))
        self.checkBoxR3.setText(QCoreApplication.translate("DialogShowColumns", u"R3", None))
        self.checkBoxHAN.setText(QCoreApplication.translate("DialogShowColumns", u"HAN", None))
        self.checkBoxSTA.setText(QCoreApplication.translate("DialogShowColumns", u"STA", None))
        self.checkBoxR5.setText(QCoreApplication.translate("DialogShowColumns", u"R5", None))
        self.checkBoxDUR.setText(QCoreApplication.translate("DialogShowColumns", u"DUR", None))
        self.checkBoxWE.setText(QCoreApplication.translate("DialogShowColumns", u"WE", None))
        self.checkBoxWeight.setText(QCoreApplication.translate("DialogShowColumns", u"Weight", None))
        self.checkBoxR6.setText(QCoreApplication.translate("DialogShowColumns", u"R6", None))
        self.checkBoxSPD.setText(QCoreApplication.translate("DialogShowColumns", u"SPD", None))
        self.checkBoxWatched.setText(QCoreApplication.translate("DialogShowColumns", u"Watched", None))
        self.checkBoxName.setText(QCoreApplication.translate("DialogShowColumns", u"Name", None))
        self.checkBoxHeight.setText(QCoreApplication.translate("DialogShowColumns", u"Height", None))
    # retranslateUi

